### PR TITLE
make redis cache (git cache) persistent

### PR DESCRIPTION
**Pull request by metalefty**
Resolves: https://github.com/AlmaLinux/build-system/issues/175

### CODE REVIEW

**Review by maccelf — APPROVED** [review]

**Comment by zklevsha** [comment]
Great point on git cacher, thanks

But I would strongly suggest use volume mounts instead bind mounts.

You\`ll need to add aditional volume to global `volumes` section and then reference it inside of redis volume configuration

Here is an example
```
diff --git a/docker-compose.yml b/docker-compose.yml
index cc23353..18a525f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -486,6 +486,8 @@ services:
     ports:
       - 6379:6379
     restart: on-failure
+    volumes:
+      - "redis:/data"
     logging:
       driver: "json-file"
       options:
@@ -525,3 +527,4 @@ services:
 
 volumes:
   frontend_node_modules:
+  redis: 
```

Also as a sidenote why did you create PR from your forket project?
I thought you are able create branches in main one

**Review by zklevsha — CHANGES_REQUESTED** [review]
Suggestion to convert bind mount into volume mount

**Comment by metalefty** [comment]
Thanks, I'll try volume mount.

> Also as a sidenote why did you create PR from your forked project?
> I thought you are able create branches in main one

Now I'm able to create branches but not able to last week. @bennyvasquez added me to the "buildsys-devs" team for the organization on Monday.

**Comment by metalefty** [comment]
Switched to volume mount.

**Review by zklevsha — APPROVED** [review]

**Pull request merged**
