### PR TITLE
Implement packages sorting in errata page

### PR DESCRIPTION
**Pull request by metalefty**
* Add ability to change sort order
* Display package checksums in errata page that was unintentionally not displayed
* Show updated packages as compact table

Merge https://github.com/AlmaLinux/errata_index/pull/4 together.

### CODE REVIEW

**Comment by metalefty** [comment]
Here is the screenshot of errata page this PR will generate:
image

**Review by maccelf — APPROVED** [review]
Looks good for me

**Comment by javihernandez** [comment]
@metalefty looks good. I'm just curious, how it'll look like when having very long package names? let's say `postgresql-test-rpm-macros-10.23-2.module_el8.8.0+3599+77865fc6.aarch64.rpm`, or `libvirt-daemon-driver-secret-8.0.0-19.2.module_el8.8.0+3585+76b9c397.alma.ppc64le.rpm`

**Comment by metalefty** [comment]
Very long package names will look like this. No horizontal scrolling anyway.

image

**Review by javihernandez — APPROVED** [review]

**Pull request merged**
